name: Deploy Cloud Resume

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ ****************W4IX }}
        aws-secret-access-key: ${{ ****************K11H }}
        aws-region: ${{ us-east-1 }}

    - name: Sync website to S3
      run: aws s3 sync ./website s3://${{ secrets.BUCKET_NAME }} --delete

    - name: Post deployment message
      run: echo "Deployment to S3 completed successfully!"
